# action.yml
name: 'Katsotaan mihin action menee lokiin'
description: 'actionyml käynnissä'
inputs:
  who-to-greet:  # Jokke
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'solutioncenter-integration-tests'
  args:
    - ${{ inputs.who-to-greet }}