
name: Jarmos Github testiä

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Jobin nimi vaikka Reiska
    steps:
      - name: Nyt kutsuu actionia ja repoa
        id: Hello
        uses: actions/checkout@v2
        with:
          who-to-greet: 'Joko Github Actions heräsi'
          
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
