
name: Jarmos Github testiä

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Jobin nimi vaikka Reiska
    
    steps:
    - name: Login to docker hub
      uses: docker/login-action@v1
      with: 
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}        
      - name: Checkout
        uses: actions/checkout@v2
      - name: next steppi
        uses: ./
        id: Hello
        with:
          who-to-greet: 'Joko Github Actions heräsi'
          
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
